# Stubs for networkx.algorithms.centrality.load (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Union

def load_centrality(G: Any, v:Any=None, cutoff:Union[int,float]=None, normalized:bool=True, weight:str=None): ...

def edge_load_centrality(G: Any, cutoff: bool = ...): ...
