# Stubs for networkx.classes (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .ordered import OrderedGraph, OrderedDiGraph, OrderedMultiGraph, OrderedMultiDiGraph
from .function import nodes, edges, degree, neighbors, number_of_nodes, number_of_edges, density, degree_histogram, is_directed, freeze, is_frozen, add_star, add_path, add_cycle, subgraph, induced_subgraph, edge_subgraph, restricted_view, reverse_view, to_directed, to_undirected, create_empty_copy, info, set_node_attributes, get_node_attributes, set_edge_attributes, get_edge_attributes, all_neighbors, non_neighbors, non_edges, common_neighbors, is_weighted, is_negatively_weighted, is_empty, nodes_with_selfloops, selfloop_edges, number_of_selfloops
from .digraph import DiGraph
from .graph import Graph
from .multidigraph import MultiDiGraph
from .multigraph import MultiGraph
